import numpy as np
import pandas as pd
import os


DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
INPUT_FILE = os.path.join(DATA_DIR, "synthetic_requests.csv")
OUTPUT_FILE = os.path.join(DATA_DIR, "ip_features.csv")


# INDIVIDUAL FEATURE FUNCTIONS
# Each function takes a group of requests for ONE IP and returns ONE number.

def compute_requests_per_min(group: pd.DataFrame) -> float:

    total_requests = len(group)

    # Calculate how long this IP was active (first request → last request)
    time_span = (group["timestamp"].max() - group["timestamp"].min()).total_seconds()

    # Convert to minutes, minimum 1 minute to avoid division by zero
    duration_minutes = max(time_span / 60.0, 1.0)

    return round(total_requests / duration_minutes, 4)


def compute_endpoint_variety(group: pd.DataFrame) -> int:

    return group["endpoint"].nunique()


def compute_error_rate(group: pd.DataFrame) -> float:

    total = len(group)
    errors = len(group[group["status_code"] >= 400])
    return round(errors / total, 4) if total > 0 else 0.0


def compute_avg_time_between_requests(group: pd.DataFrame) -> float:
    
    if len(group) < 2:
        return 0.0

    # Sort by time and compute differences between consecutive requests
    sorted_times = group["timestamp"].sort_values()
    time_diffs = sorted_times.diff().dropna().dt.total_seconds()

    return round(time_diffs.mean(), 4) if len(time_diffs) > 0 else 0.0


def compute_single_endpoint_ratio(group: pd.DataFrame) -> float:

    total = len(group)
    if total == 0:
        return 0.0

    # value_counts() returns counts sorted descending — first item is the most common
    most_common_count = group["endpoint"].value_counts().iloc[0]
    return round(most_common_count / total, 4)


def compute_user_agent_variety(group: pd.DataFrame) -> int:

    return group["user_agent"].nunique()


# MASTER FEATURE ENGINEERING FUNCTION

def engineer_features(df: pd.DataFrame) -> pd.DataFrame:

    # Step 1: Ensure timestamp is datetime (might be string if loaded from CSV)
    if df["timestamp"].dtype == "object":
        df["timestamp"] = pd.to_datetime(df["timestamp"], format="ISO8601")

    print("=" * 60)
    print("  SentinelAPI -- Feature Engineering")
    print("=" * 60)
    print(f"\n   Input: {len(df)} raw request rows from {df['ip'].nunique()} IPs")

    # Step 2: Group by IP
    grouped = df.groupby("ip")

    # Step 3: Compute features for each IP
    print("   Computing features per IP...")

    feature_rows = []
    for ip, group in grouped:
        feature_rows.append({
            "ip": ip,
            "requests_per_min": compute_requests_per_min(group),
            "endpoint_variety": compute_endpoint_variety(group),
            "error_rate": compute_error_rate(group),
            "avg_time_between_reqs": compute_avg_time_between_requests(group),
            "single_endpoint_ratio": compute_single_endpoint_ratio(group),
            "user_agent_variety": compute_user_agent_variety(group),
            # Attach labels — take the FIRST value since all rows for an IP
            # have the same label (an IP is either attack or normal)
            "is_attack": group["is_attack"].iloc[0],
            "attack_type": group["attack_type"].iloc[0],
        })

    features_df = pd.DataFrame(feature_rows)

    # Step 4: Print summary
    print(f"   Output: {len(features_df)} IP feature vectors")
    print(f"\n   Feature statistics:")
    print(features_df[["requests_per_min", "endpoint_variety", "error_rate","avg_time_between_reqs", "single_endpoint_ratio","user_agent_variety"]].describe().round(3).to_string())

    return features_df


# ENTRY POINT — Run as standalone script

if __name__ == "__main__":
    # Step 1: Load the raw data generated by data_generator.py
    if not os.path.exists(INPUT_FILE):
        print(f"ERROR: Input file not found: {INPUT_FILE}")
        print("Run 'python -m ml.data_generator' first to generate the dataset.")
        exit(1)

    print(f"Loading raw data from: {INPUT_FILE}")
    raw_df = pd.read_csv(INPUT_FILE)

    # Step 2: Run feature engineering
    features_df = engineer_features(raw_df)

    # Step 3: Save to CSV
    features_df.to_csv(OUTPUT_FILE, index=False)
    print(f"\n   Saved to: {OUTPUT_FILE}")

    # Step 4: Show feature comparison between normal and attack IPs
    print("\n" + "=" * 60)
    print("  FEATURE COMPARISON: Normal vs Attack IPs")
    print("=" * 60)

    for attack_type in ["normal", "bruteforce", "scraper", "credential_stuffing"]:
        subset = features_df[features_df["attack_type"] == attack_type]
        if len(subset) == 0:
            continue
        print(f"\n--- {attack_type.upper()} ({len(subset)} IPs) ---")
        print(subset[["requests_per_min", "endpoint_variety", "error_rate",
                       "avg_time_between_reqs", "single_endpoint_ratio",
                       "user_agent_variety"]].describe().round(3).loc[["mean", "std"]].to_string())

    # Step 5: Show a few sample rows for each type
    print("\n" + "=" * 60)
    print("  SAMPLE FEATURE VECTORS (2 per category)")
    print("=" * 60)

    for attack_type in ["normal", "bruteforce", "scraper", "credential_stuffing"]:
        subset = features_df[features_df["attack_type"] == attack_type]
        if len(subset) == 0:
            continue
        print(f"\n--- {attack_type.upper()} ---")
        sample = subset.head(2)
        print(sample.to_string(index=False))

